name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-app:v1 .
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
        aws configure set region us-east-1

    - name: Update Kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name demo-cluster

    - name: Deploy to EKS
      run: |
        cd manifests/hello-app
        kubectl apply -f manifests/hello-app/deploy.yaml -n hello-space
        kubectl apply -f manifests/hello-app/service.yaml -n hello-space
        kubectl apply -f manifests/hello-app/ingress.yaml -n hello-space
